version: '3'
services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  backend:
    build: #./backend/
        context: .
        dockerfile: ./backend/Dockerfile
    #command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
      - public:/app/public # 追加
      - tmp:/app/tmp # 追加
    #ports:
    #  - 3001:3000
    depends_on:
      - db
  front:
      build: ./frontend/
      volumes:
        - ./frontend/app:/front
      ports:
        - 3000:3000
      tty: true
      stdin_open: true
      environment:
        - CHOKIDAR_USEPOLLING=true
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/app/public # 追加
      - tmp:/app/tmp # 追加
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  data-volume:
  tmp: # 追加
  public: # 追加